### PR TITLE
Tweak wording in "Work Partitioning" in intro.tex

### PR DESCRIPTION
**Pull request by rootbeer**
The partitioning here is about the work, not the code.

Signed-off-by: Pat Tullmann <pat@tullmann.org>

### CODE REVIEW

**Comment by paulmckrcu** [comment]
Good catch!  Could you please add your "Signed-off-by" to the commit?  Please see question #5 of FAQ.txt in the perfbook top-level directory for more info.

**Comment by rootbeer** [comment]
Oops, done.  Patch is Signed-off-by me now.

**Comment by paulmckrcu** [comment]
I am sorry, but I am still not seeing it in the patch.  I am looking at your patch-1 branch.

Alternatively, just tell me what I should fill in the "name" and "email" in "Signed-off-by: name <email>" and I can add it into the patch on your patch-1 branch.

**Comment by rootbeer** [comment]
Oh, I'm an idiot ... I edited the sign-off into the github discussion, not the patch.  Been a while since I've github'd.  

I've pushed an updated commit message.  Sorry for the hassle.

**Comment by paulmckrcu** [comment]
No problem, and thank you!  I have pulled this in manually and pushed it out, which means that I "Close with comment" to stop github from nagging me.  But it is now part of perfbook, and again thank you!

**Pull request closed without merging**
